#!/usr/bin/ruby

require 'hiera'
require 'yaml'

# Get Foreman configurations and define scope
fqdn = ARGV[0]
foreman = YAML.load(`/etc/puppet/external_node_v2.rb #{fqdn}`) || {}
environment = foreman['environment'] || ''

scope = { 'environment' => environment }
# Hiera interface
hiera = Hiera.new(:config => '/etc/hiera.yaml')

# Merge Hiera configuration on top of Foreman without overwrite
classes = foreman['classes'].merge(hiera.lookup('classes', nil, scope) || {})
parameters = foreman['parameters'].merge(hiera.lookup('parameters', nil, scope) || {})
foreman['classes'] = classes
foreman['parameters'] = parameters

puts foreman.to_yaml
